before:
  hooks:
    - go mod tidy

report_sizes: true

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      # SQLite driver working on adding Windows 32-bit support
      # https://gitlab.com/cznic/sqlite/-/issues/86
      # https://pkg.go.dev/modernc.org/sqlite?utm_source=godoc#hdr-Supported_platforms_and_architectures
      - goos: windows
        goarch: "386"
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/ismailshak/transit/version.version={{.Version}}
      - -X github.com/ismailshak/transit/version.commit={{.Commit}}
      - -X github.com/ismailshak/transit/version.date={{.Date}}

archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

universal_binaries:
  - replace: false

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

brews:
  - repository:
      owner: ismailshak
      name: homebrew-tap
    folder: Formula
    goarm: "7"
    homepage: https://transitcli.com
    description: "CLI tool that interacts with local transit information"
    license: MIT
    test: |
      assert_match version.to_s, shell_output("#{bin}/transit --version")

scoops:
  - repository:
      owner: ismailshak
      name: scoop-bucket
    folder: bucket
    homepage: https://transitcli.com
    description: "CLI tool that interacts with local transit information"
    license: MIT

# The lines beneath this are called `modelines`. See `:help modeline`
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
