before:
  hooks:
    - go mod tidy

report_sizes: true

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/ismailshak/transit/version.version={{.Version}}
      - -X github.com/ismailshak/transit/version.commit={{.Commit}}
      - -X github.com/ismailshak/transit/version.date={{.Date}}

archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

universal_binaries:
  - replace: true

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

brews:
  - repository:
      owner: ismailshak
      name: homebrew-tap
      branch: "{{.ProjectName}}-{{.Version}}"
      pull_request:
        enabled: true
        draft: false
        base:
          owner: ismailshak
          name: homebrew-tap
          branch: main
    folder: Formula
    goarm: "7"
    homepage: https://transitcli.com
    description: "CLI tool that interacts with local transit information"
    license: MIT
    test: |
      assert_match version.to_s, shell_output("#{bin}/transit --version")

scoops:
  - repository:
      owner: ismailshak
      name: scoop-bucket
      branch: "{{.ProjectName}}-{{.Version}}"
      pull_request:
        enabled: true
        draft: false
        base:
          owner: ismailshak
          name: scoop-bucket
          branch: main
    folder: bucket
    homepage: https://transitcli.com
    description: "CLI tool that interacts with local transit information"
    license: MIT

# The lines beneath this are called `modelines`. See `:help modeline`
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
