on: [pull_request]
name: Verify

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Set up Go
        uses: ./.github/actions/setup-go
      - name: Build binary
        run: mise run build
      - name: Lint project
        uses: golangci/golangci-lint-action@v9
        with:
          install-mode: "none" # Installed by mise
          only-new-issues: true
